
file(MAKE_DIRECTORY "${CASE_DIR}")
foreach(mode pass fail)
    execute_process(COMMAND "${COMPILER}" -std=c++20 "-I${ROOT}/include" -fsyntax-only
        "${ROOT}/tests/compile_${mode}/${CASE_NAME}.cpp"
        RESULT_VARIABLE result OUTPUT_VARIABLE out ERROR_VARIABLE err TIMEOUT 30)
    file(WRITE "${CASE_DIR}/${mode}.log" "${out}\n${err}")
    if(mode STREQUAL "pass")
        if(NOT "${result}" STREQUAL "0")
            message(FATAL_ERROR "positive control failed: ${out}${err}")
        endif()
    else()
        if(NOT "${result}" MATCHES "^[0-9]+$" OR "${result}" STREQUAL "0")
            message(FATAL_ERROR "negative control did not fail normally: ${result}")
        endif()
        if(NOT "${out}${err}" MATCHES "${TOKEN}")
            message(FATAL_ERROR "expected QLog constraint missing: ${out}${err}")
        endif()
    endif()
endforeach()
